# PYTHON FOR AI

# HELLO PROGRAM
print("Hello World")

# VARIABLES
num = 12
name = "Atau"
print(num)
print(name)


# DATA TYPES
a = 10
b = 20.5
c = "Atau"
d = True
e = False
f = 1+2j
g = [1, 2, 3]  # list
h = (1, 2, 3)  # tuple
i = {"name": "Atau", "age": 20} # dictionary
j = {"name", "age", "gender"} # set
 
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(type(f))
print(type(g))
print(type(h))
print(type(i))
print(type(j))

# OPERATORS
# Arithmatic Operators
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)
print(a ** b)
print(a // b)

# conditional statment
if a > b:
    print("a is greater than b")
elif a == b:
    print("a is equal to b")
else:
    print("a is less than b")


